name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Running tests
      run: |
        echo "Running tests"
        # Add your test commands here, e.g.:
        # pytest tests/
        echo "Tests passed"
      working-directory: ./to-do-list-cicd

    - name: Building the code
      run: |
        echo "Building the code"
        docker build -t to-do .
      working-directory: ./to-do-list-cicd

    - name: Pushing the code to Docker Hub
      run: |
        echo "Pushing the code to Docker Hub"
        docker tag to-do ${{ secrets.DOCKERHUB_USERNAME }}/to-do:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/to-do:latest
      working-directory: ./to-do-list-cicd

    - name: Deploying the code
      run: |
        echo "Deploying the code to agents"
        docker-compose down
        docker-compose up -d
      working-directory: ./to-do-list-cicd

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: ./to-do-list-cicd/public
